repos:
  - repo: https://github.com/agriffis/pre-commit-conventional
    rev: v1.0.0
    hooks:
      - id: conventional-commit

  - repo: local
    hooks:
      - id: test
        name: test.bash
        entry: ./test.bash
        always_run: true
        pass_filenames: false
        stages: [push]
        language: system
